production: &default
  adapter: postgresql
  database: <%= ENV['DB_NAME'] %>
  host:     <%= ENV['DB_HOST'] %>
  port:     <%= ENV['DB_PORT'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  encoding: utf8
  timeout: 2000

development:
  <<: *default
  pool: <%= ENV['DB_POOL'] || 5 %>

test: &test
  <<: *default
  database: <%= ENV['DB_TEST_NAME'] %>
